// SPDX-FileCopyrightText: Azahar Emulator Project
// Copyright(c) 2026: PalindromicBreadLoaf(palindromicbreadloaf@tuta.com)
// SPDX-License-Identifier: GPL-2.0-or-later

// Generated by font/bake_overlay_font.py from Roboto-Regular.ttf (Apache-2.0). Do not edit by hand.
//
// See the above file for more information.

#pragma once

#include <cstddef>

#include "common/common_types.h"

namespace Vulkan::OverlayFont {

struct Glyph {
    float u0, v0, u1, v1;      // Atlas texture coordinates.
    float xoff, yoff;          // Bake-pixel offset from the pen to the quad.
    float w, h;                // Quad size in bake pixels.
    float xadvance;            // Horizontal pen advance in bake pixels.
};

constexpr int kFirstChar = 32;
constexpr int kLastChar = 126;
constexpr int kGlyphCount = 95;

constexpr int kAtlasWidth = 512;
constexpr int kAtlasHeight = 264;

constexpr float kBakePixelHeight = 48.0;
constexpr float kAscent = 45.0;
constexpr float kDescent = 12.0;
constexpr float kLineHeight = 57.0;

constexpr float kWhiteU = 0.076172f;
constexpr float kWhiteV = 0.928030f;

extern const Glyph kGlyphs[kGlyphCount];
extern const unsigned char kAtlas[kAtlasWidth * kAtlasHeight];

// Builds a larger atlas from Switch shared fonts when available. The generated Roboto ASCII atlas
// above remains the fallback for non-Switch builds or font-loading failures.
bool Initialize();
void Shutdown();

int AtlasWidth();
int AtlasHeight();
const unsigned char* AtlasData();
std::size_t AtlasSize();

float BakePixelHeight();
float Ascent();
float Descent();
float LineHeight();
float WhiteU();
float WhiteV();

const Glyph& GlyphFor(u32 codepoint);

inline const Glyph& GlyphFor(char c) {
    return GlyphFor(static_cast<u32>(static_cast<unsigned char>(c)));
}

} // namespace Vulkan::OverlayFont
